-- ============================================
-- File: 02_schema.sql
-- Description: Create base PostgreSQL tables converted from the live SQL Server schema without foreign keys.
-- Run order: 2 of 10
-- Dependencies: 01_extensions.sql
-- ============================================
-- Tables migrated: 17
-- Views migrated: 0
-- Functions migrated: 0
-- Stored Procedures migrated: 79
-- Triggers migrated: 0
-- Indexes migrated: 33
-- Known incompatibilities: __ef_migrations_history omitted because Supabase deployment should not carry SQL Server EF bookkeeping.
-- Manual review required: Review default timezone semantics on timestamptz columns if the source application assumed SQL Server local server time.


BEGIN;

CREATE TABLE IF NOT EXISTS public.tbl_admin_note (
    admin_note_id bigserial NOT NULL,
    admin_user_id bigint NOT NULL,
    target_user_id bigint NOT NULL,
    note_text varchar(512) NOT NULL,
    note_date timestamptz NOT NULL DEFAULT NOW(),
    tag varchar(64),
    comments varchar(256),
    sort_order integer NOT NULL DEFAULT 0,
    ip_address varchar(64) NOT NULL DEFAULT '127.0.0.1',
    created_by varchar(128) NOT NULL DEFAULT 'Admin',
    date_created timestamptz NOT NULL DEFAULT NOW(),
    updated_by varchar(128),
    last_updated timestamptz,
    deleted_by varchar(128),
    date_deleted timestamptz,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_tbl_admin_note_admin_note_id PRIMARY KEY (admin_note_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_dashboard_metric (
    dashboard_metric_id bigserial NOT NULL,
    metric_date date NOT NULL,
    total_users integer NOT NULL DEFAULT 0,
    active_sessions_today integer NOT NULL DEFAULT 0,
    total_scripts_uploaded integer NOT NULL DEFAULT 0,
    total_mistakes_recorded integer NOT NULL DEFAULT 0,
    tag varchar(64),
    comments varchar(256),
    sort_order integer NOT NULL DEFAULT 0,
    ip_address varchar(64) NOT NULL DEFAULT '127.0.0.1',
    created_by varchar(128) NOT NULL DEFAULT 'Admin',
    date_created timestamptz NOT NULL DEFAULT NOW(),
    updated_by varchar(128),
    last_updated timestamptz,
    deleted_by varchar(128),
    date_deleted timestamptz,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_tbl_dashboard_metric_dashboard_metric_id PRIMARY KEY (dashboard_metric_id),
    CONSTRAINT uk_tbl_dashboard_metric_metric_date UNIQUE (metric_date)
);

CREATE TABLE IF NOT EXISTS public.tbl_listener_feedback (
    listener_feedback_id bigserial NOT NULL,
    session_id bigint NOT NULL,
    turn_index integer NOT NULL,
    from_user_id bigint NOT NULL,
    target_user_id bigint NOT NULL,
    feedback_tag varchar(32) NOT NULL,
    feedback_at timestamptz NOT NULL DEFAULT NOW(),
    tag varchar(64),
    comments varchar(256),
    sort_order integer NOT NULL DEFAULT 0,
    ip_address varchar(64) NOT NULL DEFAULT '127.0.0.1',
    created_by varchar(128) NOT NULL DEFAULT 'Admin',
    date_created timestamptz NOT NULL DEFAULT NOW(),
    updated_by varchar(128),
    last_updated timestamptz,
    deleted_by varchar(128),
    date_deleted timestamptz,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_tbl_listener_feedback_listener_feedback_id PRIMARY KEY (listener_feedback_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_mistake (
    mistake_id bigserial NOT NULL,
    user_id bigint NOT NULL,
    session_id bigint NOT NULL,
    utterance_id bigint NOT NULL,
    script_id bigint NOT NULL,
    utterance_text varchar(512) NOT NULL,
    spoken_text varchar(512),
    mistake_type varchar(32) NOT NULL,
    mistake_detail varchar(256),
    grammar_tag varchar(64),
    context_tag varchar(64),
    correction_text varchar(512),
    practice_count integer NOT NULL DEFAULT 0,
    is_resolved boolean NOT NULL DEFAULT FALSE,
    first_occurrence timestamptz NOT NULL DEFAULT NOW(),
    last_attempt timestamptz,
    tag varchar(64),
    comments varchar(256),
    sort_order integer NOT NULL DEFAULT 0,
    ip_address varchar(64) NOT NULL DEFAULT '127.0.0.1',
    created_by varchar(128) NOT NULL DEFAULT 'Admin',
    date_created timestamptz NOT NULL DEFAULT NOW(),
    updated_by varchar(128),
    last_updated timestamptz,
    deleted_by varchar(128),
    date_deleted timestamptz,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_tbl_mistake_mistake_id PRIMARY KEY (mistake_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_refresh_token (
    refresh_token_id bigserial NOT NULL,
    user_id bigint NOT NULL,
    token varchar(512) NOT NULL,
    expires_at timestamptz NOT NULL,
    is_revoked boolean NOT NULL DEFAULT FALSE,
    revoked_at timestamptz,
    device_info varchar(256),
    tag varchar(64),
    comments varchar(256),
    sort_order integer NOT NULL DEFAULT 0,
    ip_address varchar(64) NOT NULL DEFAULT '127.0.0.1',
    created_by varchar(128) NOT NULL DEFAULT 'Admin',
    date_created timestamptz NOT NULL DEFAULT NOW(),
    updated_by varchar(128),
    last_updated timestamptz,
    deleted_by varchar(128),
    date_deleted timestamptz,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_tbl_refresh_token_refresh_token_id PRIMARY KEY (refresh_token_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_repractice_session (
    repractice_session_id bigserial NOT NULL,
    user_id bigint NOT NULL,
    source_session_id bigint NOT NULL,
    total_mistakes integer NOT NULL DEFAULT 0,
    completed_rounds integer NOT NULL DEFAULT 0,
    improvement_percent numeric(5,2) NOT NULL DEFAULT 0,
    status varchar(16) NOT NULL DEFAULT 'PENDING',
    generated_date timestamptz NOT NULL DEFAULT NOW(),
    tag varchar(64),
    comments varchar(256),
    sort_order integer NOT NULL DEFAULT 0,
    ip_address varchar(64) NOT NULL DEFAULT '127.0.0.1',
    created_by varchar(128) NOT NULL DEFAULT 'Admin',
    date_created timestamptz NOT NULL DEFAULT NOW(),
    updated_by varchar(128),
    last_updated timestamptz,
    deleted_by varchar(128),
    date_deleted timestamptz,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_tbl_repractice_session_repractice_session_id PRIMARY KEY (repractice_session_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_repractice_utterance (
    repractice_utterance_id bigserial NOT NULL,
    repractice_session_id bigint NOT NULL,
    mistake_id bigint NOT NULL,
    original_utterance_id bigint NOT NULL,
    english_text varchar(512) NOT NULL,
    hint_text varchar(512),
    mistake_type varchar(32) NOT NULL,
    mistake_detail varchar(256),
    correction_note varchar(512),
    attempt_count integer NOT NULL DEFAULT 0,
    best_score numeric(5,2) NOT NULL DEFAULT 0,
    last_score numeric(5,2) NOT NULL DEFAULT 0,
    is_resolved boolean NOT NULL DEFAULT FALSE,
    tag varchar(64),
    comments varchar(256),
    sort_order integer NOT NULL DEFAULT 0,
    ip_address varchar(64) NOT NULL DEFAULT '127.0.0.1',
    created_by varchar(128) NOT NULL DEFAULT 'Admin',
    date_created timestamptz NOT NULL DEFAULT NOW(),
    updated_by varchar(128),
    last_updated timestamptz,
    deleted_by varchar(128),
    date_deleted timestamptz,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_tbl_repractice_utterance_repractice_utterance_id PRIMARY KEY (repractice_utterance_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_script (
    script_id bigserial NOT NULL,
    script_title varchar(128) NOT NULL,
    category varchar(64) NOT NULL,
    grammar_focus_tag varchar(64) NOT NULL,
    context_tag varchar(64) NOT NULL,
    complexity_level smallint NOT NULL,
    target_age_group varchar(32) NOT NULL,
    hint_language varchar(32) NOT NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    uploaded_date timestamptz NOT NULL DEFAULT NOW(),
    uploaded_by_user_id bigint NOT NULL,
    version integer NOT NULL DEFAULT 1,
    utterance_count integer NOT NULL DEFAULT 0,
    tag varchar(64),
    comments varchar(256),
    sort_order integer NOT NULL DEFAULT 0,
    ip_address varchar(64) NOT NULL DEFAULT '127.0.0.1',
    created_by varchar(128) NOT NULL DEFAULT 'Admin',
    date_created timestamptz NOT NULL DEFAULT NOW(),
    updated_by varchar(128),
    last_updated timestamptz,
    deleted_by varchar(128),
    date_deleted timestamptz,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_tbl_script_script_id PRIMARY KEY (script_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_script_version (
    script_version_id bigserial NOT NULL,
    script_id bigint NOT NULL,
    version_number integer NOT NULL,
    version_notes varchar(256),
    uploaded_by_user_id bigint NOT NULL,
    uploaded_date timestamptz NOT NULL DEFAULT NOW(),
    tag varchar(64),
    comments varchar(256),
    sort_order integer NOT NULL DEFAULT 0,
    ip_address varchar(64) NOT NULL DEFAULT '127.0.0.1',
    created_by varchar(128) NOT NULL DEFAULT 'Admin',
    date_created timestamptz NOT NULL DEFAULT NOW(),
    updated_by varchar(128),
    last_updated timestamptz,
    deleted_by varchar(128),
    date_deleted timestamptz,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_tbl_script_version_script_version_id PRIMARY KEY (script_version_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_session (
    session_id bigserial NOT NULL,
    session_name varchar(128) NOT NULL,
    join_code varchar(8) NOT NULL,
    session_mode varchar(64) NOT NULL,
    max_members smallint NOT NULL DEFAULT 4,
    session_duration integer NOT NULL,
    host_user_id bigint NOT NULL,
    script_id bigint NOT NULL,
    status varchar(16) NOT NULL DEFAULT 'LOBBY',
    room_expiry_minutes integer NOT NULL,
    room_expires_at timestamptz,
    started_date timestamptz,
    ended_date timestamptz,
    actual_duration_sec integer,
    tag varchar(64),
    comments varchar(256),
    sort_order integer NOT NULL DEFAULT 0,
    ip_address varchar(64) NOT NULL DEFAULT '127.0.0.1',
    created_by varchar(128) NOT NULL DEFAULT 'Admin',
    date_created timestamptz NOT NULL DEFAULT NOW(),
    updated_by varchar(128),
    last_updated timestamptz,
    deleted_by varchar(128),
    date_deleted timestamptz,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_tbl_session_session_id PRIMARY KEY (session_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_session_member (
    session_member_id bigserial NOT NULL,
    session_id bigint NOT NULL,
    user_id bigint NOT NULL,
    slot_index smallint NOT NULL,
    slot_name varchar(64) NOT NULL,
    is_ready boolean NOT NULL DEFAULT FALSE,
    is_host boolean NOT NULL DEFAULT FALSE,
    joined_at timestamptz,
    left_at timestamptz,
    is_active boolean NOT NULL DEFAULT TRUE,
    tag varchar(64),
    comments varchar(256),
    sort_order integer NOT NULL DEFAULT 0,
    ip_address varchar(64) NOT NULL DEFAULT '127.0.0.1',
    created_by varchar(128) NOT NULL DEFAULT 'Admin',
    date_created timestamptz NOT NULL DEFAULT NOW(),
    updated_by varchar(128),
    last_updated timestamptz,
    deleted_by varchar(128),
    date_deleted timestamptz,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_tbl_session_member_session_member_id PRIMARY KEY (session_member_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_turn_state (
    turn_state_id bigserial NOT NULL,
    session_id bigint NOT NULL,
    turn_index integer NOT NULL,
    total_turns integer NOT NULL,
    active_member_id bigint NOT NULL,
    active_slot_index smallint NOT NULL,
    utterance_id bigint NOT NULL,
    re_read_allowed boolean NOT NULL DEFAULT TRUE,
    re_read_count integer NOT NULL DEFAULT 0,
    max_re_reads integer NOT NULL DEFAULT 2,
    turn_status varchar(16) NOT NULL DEFAULT 'ACTIVE',
    turn_started_at timestamptz,
    turn_completed_at timestamptz,
    tag varchar(64),
    comments varchar(256),
    sort_order integer NOT NULL DEFAULT 0,
    ip_address varchar(64) NOT NULL DEFAULT '127.0.0.1',
    created_by varchar(128) NOT NULL DEFAULT 'Admin',
    date_created timestamptz NOT NULL DEFAULT NOW(),
    updated_by varchar(128),
    last_updated timestamptz,
    deleted_by varchar(128),
    date_deleted timestamptz,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_tbl_turn_state_turn_state_id PRIMARY KEY (turn_state_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_user (
    user_id bigserial NOT NULL,
    full_name varchar(128) NOT NULL,
    mobile_number varchar(16) NOT NULL,
    email varchar(128),
    password_hash varchar(512),
    age_group varchar(32) NOT NULL,
    preferred_hint_language varchar(32) NOT NULL,
    avatar_url varchar(256),
    group_code varchar(32),
    role varchar(16) NOT NULL DEFAULT 'USER',
    daily_streak_count integer NOT NULL DEFAULT 0,
    total_sessions_played integer NOT NULL DEFAULT 0,
    last_login_date timestamptz,
    is_active boolean NOT NULL DEFAULT TRUE,
    registration_date timestamptz NOT NULL DEFAULT NOW(),
    tag varchar(64),
    comments varchar(256),
    sort_order integer NOT NULL DEFAULT 0,
    ip_address varchar(64) NOT NULL DEFAULT '127.0.0.1',
    created_by varchar(128) NOT NULL DEFAULT 'Admin',
    date_created timestamptz NOT NULL DEFAULT NOW(),
    updated_by varchar(128),
    last_updated timestamptz,
    deleted_by varchar(128),
    date_deleted timestamptz,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_tbl_user_user_id PRIMARY KEY (user_id),
    CONSTRAINT uk_tbl_user_mobile_number UNIQUE (mobile_number)
);

CREATE TABLE IF NOT EXISTS public.tbl_user_badge (
    user_badge_id bigserial NOT NULL,
    user_id bigint NOT NULL,
    badge_code varchar(64) NOT NULL,
    badge_name varchar(128) NOT NULL,
    earned_date timestamptz NOT NULL DEFAULT NOW(),
    tag varchar(64),
    comments varchar(256),
    sort_order integer NOT NULL DEFAULT 0,
    ip_address varchar(64) NOT NULL DEFAULT '127.0.0.1',
    created_by varchar(128) NOT NULL DEFAULT 'Admin',
    date_created timestamptz NOT NULL DEFAULT NOW(),
    updated_by varchar(128),
    last_updated timestamptz,
    deleted_by varchar(128),
    date_deleted timestamptz,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_tbl_user_badge_user_badge_id PRIMARY KEY (user_badge_id),
    CONSTRAINT uk_tbl_user_badge_user_id_badge_code UNIQUE (user_id, badge_code)
);

CREATE TABLE IF NOT EXISTS public.tbl_user_streak (
    user_streak_id bigserial NOT NULL,
    user_id bigint NOT NULL,
    streak_date date NOT NULL,
    session_count integer NOT NULL DEFAULT 0,
    practice_minutes integer NOT NULL DEFAULT 0,
    tag varchar(64),
    comments varchar(256),
    sort_order integer NOT NULL DEFAULT 0,
    ip_address varchar(64) NOT NULL DEFAULT '127.0.0.1',
    created_by varchar(128) NOT NULL DEFAULT 'Admin',
    date_created timestamptz NOT NULL DEFAULT NOW(),
    updated_by varchar(128),
    last_updated timestamptz,
    deleted_by varchar(128),
    date_deleted timestamptz,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_tbl_user_streak_user_streak_id PRIMARY KEY (user_streak_id),
    CONSTRAINT uk_tbl_user_streak_user_id_streak_date UNIQUE (user_id, streak_date)
);

CREATE TABLE IF NOT EXISTS public.tbl_utterance (
    utterance_id bigserial NOT NULL,
    script_id bigint NOT NULL,
    sequence_id integer NOT NULL,
    speaker_label varchar(64) NOT NULL,
    english_text varchar(512) NOT NULL,
    hint_text varchar(512),
    grammar_tag varchar(64),
    context_tag varchar(64),
    focus_word varchar(64),
    pronunciation_note varchar(256),
    tag varchar(64),
    comments varchar(256),
    sort_order integer NOT NULL DEFAULT 0,
    ip_address varchar(64) NOT NULL DEFAULT '127.0.0.1',
    created_by varchar(128) NOT NULL DEFAULT 'Admin',
    date_created timestamptz NOT NULL DEFAULT NOW(),
    updated_by varchar(128),
    last_updated timestamptz,
    deleted_by varchar(128),
    date_deleted timestamptz,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_tbl_utterance_utterance_id PRIMARY KEY (utterance_id)
);

CREATE TABLE IF NOT EXISTS public.tbl_voice_analysis (
    voice_analysis_id bigserial NOT NULL,
    session_id bigint NOT NULL,
    user_id bigint NOT NULL,
    turn_index integer NOT NULL,
    utterance_id bigint NOT NULL,
    transcribed_text varchar(512),
    expected_text varchar(512) NOT NULL,
    fluency_score numeric(5,2) NOT NULL DEFAULT 0,
    confidence_score numeric(5,2) NOT NULL DEFAULT 0,
    speaking_speed_wpm integer NOT NULL DEFAULT 0,
    pause_count integer NOT NULL DEFAULT 0,
    hesitation_words varchar(256),
    repeated_words varchar(256),
    grammar_errors_json varchar(512),
    pronunciation_json varchar(512),
    overall_score numeric(5,2) NOT NULL DEFAULT 0,
    recorded_at timestamptz NOT NULL DEFAULT NOW(),
    tag varchar(64),
    comments varchar(256),
    sort_order integer NOT NULL DEFAULT 0,
    ip_address varchar(64) NOT NULL DEFAULT '127.0.0.1',
    created_by varchar(128) NOT NULL DEFAULT 'Admin',
    date_created timestamptz NOT NULL DEFAULT NOW(),
    updated_by varchar(128),
    last_updated timestamptz,
    deleted_by varchar(128),
    date_deleted timestamptz,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_tbl_voice_analysis_voice_analysis_id PRIMARY KEY (voice_analysis_id)
);

COMMIT;
